services:
  app:
    build: .
    image: easy-knowledge-retriever:latest
    container_name: easy_knowledge_retriever
    ports:
      - "85:80"
    volumes:
      - ./rag_data:/app/rag_data
      - ./documents:/app/documents
    env_file:
      - .env
    environment:
      # Surcharge optionnelle si nécessaire, mais les defaults du Dockerfile sont bons
      - EKR_WORKING_DIR=/app/rag_data
      - EKR_SOURCE_DIR=/app/documents
    restart: unless-stopped
